apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: mutate-test
  namespace: lovejoy
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/netexec:1.0
    imagePullPolicy: Always
    name: netexec
    resources:
      requests:
        cpu: "1"
        memory: 1000Mi
